### ISSUE TITLE
Documentation on how to install this library?

### ISSUE THREAD

**Issue by jhlgns** [SkinnyMind/libgit2dart#15]
Hello, thanks for providing this library!
I am considering to use it for my project!
However, I am pretty new to Dart and Flutter, so I am a bit lost about how to install it.
It is not listed in the official repositories (pub.dev), so I guess I'd have to install it 'by hand' - do you have some hint on how to do that?
Thanks!

**Comment by SkinnyMind** [comment]
Hello! Glad that you consider using that library. It is not published to pub.dev yet because of some big refactor i'm planning to do in the beginning of the next year (that refactor depends on some new functionality that will land in dart language). So there's that, you might want to wait for a couple months untill i'll do refactor and publish it, or if you are really eager to start using library you can install dependencies to your project from github by simply adding these lines to your pubspec.yaml:
```yaml
libgit2dart:
    git:
      url: https://github.com/SkinnyMind/libgit2dart
```

You can read more about using packages [here](https://docs.flutter.dev/development/packages-and-plugins/using-packages#dependencies-on-unpublished-packages).

**Comment by jhlgns** [comment]
Hey, that's pretty cool, Dart never fails to amaze me so far!
If libgit2dart is usable at this point, I'd now go ahead and install the git package the way you described.
It does not have to be completely stable in all it does, since my project is only a prototype for now, which I am writing for my bachelor thesis.
By the time I get to implement the actual tool, the refactor is probably already done and I could use libgit2dart in production!
Thank you very much!

**Comment by SkinnyMind** [comment]
Package is usable right now, it have almost all of the bindings implemented. Refactor i'll do will remove the need to call `free()` method on objects that require it, greatly simplifying code, since you'll no longer need to worry about possible memory leaks.

Glad i could help!
